coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

ignore:
  - "tests/"
  - "**/__pycache__/"
  - "**/venv/"
  - "**/.venv/"
  - "setup.py"

comment:
  layout: "header, diff, flags, files"
  behavior: default
  require_changes: false
