# generated by datamodel-codegen:
#   timestamp: 2025-10-11T09:33:38+00:00

from collections.abc import Sequence
from enum import Enum
from typing import Annotated

from pydantic import BaseModel, Field, conint, constr


class Call(BaseModel):
    name: Annotated[str, constr(min_length=1)] = Field(
        ...,
        description="Called function/method name",
        examples=["AsyncIOMotorClient", "logger.debug", "self.validate"],
    )
    line: Annotated[int, conint(ge=1)] = Field(
        ..., description="Line number where call occurs (1-indexed)"
    )
    external: bool = Field(
        ..., description="True if call is to external library, false if internal"
    )
    module: str | None = Field(
        None,
        description="Import module name (if external)",
        examples=["motor.motor_asyncio", "logging", "fastapi"],
    )


class Type(Enum):
    config = "config"
    variable = "variable"
    attribute = "attribute"


class Reference(BaseModel):
    name: Annotated[str, constr(min_length=1)] = Field(
        ...,
        description="Referenced variable/attribute name (may include dots for chained access)",
        examples=["settings.mongodb_url", "self.client", "config.database.host"],
    )
    line: Annotated[int, conint(ge=1)] = Field(
        ..., description="Line number where reference occurs (1-indexed)"
    )
    type: Type = Field(
        ..., description="Type of reference", examples=["config", "variable", "attribute"]
    )
    target: Annotated[str, constr(pattern=r"^.+:[0-9]+-[0-9]+$")] | None = Field(
        None,
        description=(
            "Target file/location if reference can be resolved (e.g., config file location)"
        ),
        examples=["python/config/settings.py:MongoDBSettings", "kotlin/config/AppConfig.kt:15-20"],
    )


class Complexity(BaseModel):
    cyclomatic: Annotated[int, conint(ge=1)] = Field(
        ...,
        description="Cyclomatic complexity (McCabe metric: 1 + decision nodes)",
        examples=[1, 2, 5, 10],
    )
    lines: Annotated[int, conint(ge=1)] = Field(
        ..., description="Lines of code (end_line - start_line + 1)", examples=[5, 21, 50, 100]
    )
    nesting_depth: Annotated[int, conint(ge=0)] = Field(
        ...,
        description="Maximum nesting depth of control structures (if/while/for)",
        examples=[0, 1, 2, 3],
    )


class ASTMetadata(BaseModel):
    calls: Sequence[Call] = Field(
        ..., description="Function/method calls found in this code object"
    )
    references: Sequence[Reference] = Field(
        ..., description="Variable/config/attribute references found in this code object"
    )
    complexity: Complexity = Field(..., description="Code complexity metrics computed from AST")
